### ISSUE TITLE
기초 베이스 코드 및 환경 구성

### ISSUE THREAD

**Issue by AppliedAlpha** [AppliedAlpha/Brick-Pong#1]
- 게임이 기본적으로 돌아가기 위한 기초 SFML 환경, Window 및 프로그램 기초 구조를 구성해야 함.
- 기초 환경이 master 브랜치에 구성되면 그 때부터 Task Flow를 구상하고 진행할 것.

- 추가 회의 안건
    - GitHub Flow를 어떻게 구성할 지에 대해서?
    - 코드 스타일 (PascalCase, camelCase, snake_case 등 이름 구성, 공백 작성 요령, 네이밍 작성법 등...) 어떻게 할지?
    - 게임 기획 및 개발 분야, 역할 분담을 어떻게 할 것인지에 대해서?

**Comment by AppliedAlpha** [comment]
### 5/9 회의 결과
> 해당 내용은 Notion 회의록 '5월 9일 임시 회의' 페이지에서도 확인할 수 있다.

- 회의 안건
    - GitHub Flow 구성
        - local에서는 자유롭게 (master, feature 등)
        - remote (origin)로 올릴 때 PR (Pull Request) **필수적으로** 하기
        - release는 branch 따로 생성하지 않고, tag와 (GitHub 자체) Release 기능으로 관리
        
   - 코드 스타일 획일화
       - [Google C++ Style (Naming) Guide](https://google.github.io/styleguide/cppguide.html#Naming) 를 우선적으로 보고 맞추는 방향으로 진행
       - 주석 등은 최대한 1줄 이내로 작성하는 것이 좋을 듯함
       - 줄 바꾸기 (중괄호 열기)는 차후 논의

<br />

- 해당 Issue에서 남은 작업
    

- [x] 기획 (@OruteZ )
- [x] 기초 베이스 코드, 환경 구성 완료하고 master 브랜치에 올리기 (@AppliedAlpha )
- [x] SFML 기초 학습 및 방향성 구상, 아이디어 브레인스토밍 (@Kimhyeog , @cba700 )
- [x] 해당 준비가 완료되면 본격적으로 pull하여 분업 시작

### >> Deadline: 5/12(일)

**Comment by AppliedAlpha** [comment]
- 화면 표출을 위한 State 클래스, 화면들 관리 및 전환을 위한 GameManager (게임 전체 관리자) 클래스를 만들었습니다.
- 해당 작업 상황 [master 브랜치에 Push 하였습니다.](https://github.com/AppliedAlpha/Brick-Pong/commit/bf46047eb209f065da8bb73a478aa1911a518e14)
- 각자 Pull하셔서 로컬에서 잘 실행되는지 확인해주시고, 차후 기초 기획이 완료되면 작업 분담하여 개발을 본격적으로 시작할 예정입니다.

<br />

기초적인 실행 원리는 다음과 같습니다.
- GameManager는 게임 실행에 있어서 장면들을 전환하기 위한 최상위 관리 클래스입니다.
    - 게임 창이 켜져있는 동안에는 GameManager가 최상단에서 계속 loop를 돌면서, 표시 중인 화면(State)에 대한 Update & Render를 진행해줍니다.
    - 이러한 화면/장면(State)들은 GameManager 내부에 멤버 변수로 저장된 `std::deque<State*> states`라는 덱(Deque)에서 관리합니다. 
    - 만약 덱에 화면(State)이 있다면 가장 맨 앞에 있는 화면(State)에 대해 Update & Render를 진행합니다.
    - 덱에 더 이상 남은 화면이 없다면 프로그램이 종료되었다는 의미입니다. 즉, GameManager도 역할 수행을 종료하고 소멸합니다.

- State는 화면에 표시되는 장면 하나하나 그 자체를 구성하는 클래스입니다.
    - MainMenuState, GameState, OptionState 등 다양한 화면이 존재할 수 있습니다. (이들은 모두 State라는 클래스를 상속받습니다.)
    - State 안에 있는 정보가 게임 화면에 출력되는 과정은 다음과 같습니다.
        - 한 프레임이 지날 떼마다 Update와 Render가 호출됩니다.
        - Update는 방금 지나간 한 프레임의 시간(dt) 동안 변화한 현재 화면(State)의 정보를 갱신합니다. 가령 공이 움직였다면 공의 좌표 값이 바뀌는 등 State에서 관리하는 변수 값이 여기서 변하게 됩니다.
        - Render는 갱신한 정보를 화면에 다시 그리는 역할을 수행합니다. 화면을 지우고 > 요소들을 순서대로 그리고 > 화면에 표시하는 식으로 진행이 됩니다.

더 궁금하신 점 있으시면 말씀해주세요. 여튼 확인해주시고 여기 아래에 코멘트 남겨주시면 감사하겠습니다.
@OruteZ @Kimhyeog @cba700 

![image](https://github.com/AppliedAlpha/Brick-Pong/assets/36326864/71080857-751c-458f-af6f-51be7a090541)

**Comment by OruteZ** [comment]
풀 받아서 잘 돌아가는거 확인했습니다.

**Comment by cba700** [comment]
확인했습니다

**Comment by AppliedAlpha** [comment]
베이스 환경 구성을 완료하였고 차후 세부 기획으로 넘어가서 분업할 예정입니다.

세부 기획 & 분업 이슈 링크: [Issue #3](https://github.com/AppliedAlpha/Brick-Pong/issues/3)
