### ISSUE TITLE
기획서 작성

### ISSUE THREAD

**Issue by OruteZ** [AppliedAlpha/Brick-Pong#2]

**Comment by OruteZ** [comment]
기획서 작성 완료했습니다. 전체적인 클라이언트 게임의 흐름과 룰, 공식에 대해서 작성해두었습니다. 
각자 한번씩 확인 후, 코멘트 부탁드립니다.

@AppliedAlpha @Kimhyeog @cba700 
https://brick-pong.notion.site/BrickPong-2315890adff4438183cf48facc08321b?pvs=4

**Comment by AppliedAlpha** [comment]
확인했습니다. 해당 내용에 대해 보충해주시면 더 좋을 것 같습니다.

- 플레이 흐름의 '맵 선택' 장면 부분에서 (만약 볼륨 상의 문제가 없다면) Circle/One-Line/Classic 옵션을 선택할 수 있는데, 해당 옵션들에 대한 맵은 어떻게 구성되나요?
- 경기 화면에서 필요한 객체들은 각각 어떤 클래스들로 구성시킬 수 있나요? 또한 해당 클래스들은 어떤 속성과 메소드를 지니게 될까요?

**Comment by OruteZ** [comment]
당장의 결과물이 어떻게 나올지 모든 팀원의 머릿 속에 같은 장면이 그려져야 하고, 따라서 상세한 부분을 제외한 핵심적 부분들에 대한 기획서입니다.

맵의 디자인이 어떻게 설계되어 있을지, 경기화면에서 어떤 클래스들을 구현하고 적용하게 될 지는 추후 회의, 담당자의 작업을 통해서 정하게 될 것 같습니다.

모든 기획서가 여기서 종료되진 않으며, 작업 중에 필요에 따라서 문서는 지속적으로 작성할 예정입니다.

**Comment by OruteZ** [comment]
빌드가 완성됨에 따라서 해당 이슈를 종료합니다.
