### ISSUE TITLE
화면에 공 띄우기 (김형준)

### ISSUE THREAD

**Issue by Kimhyeog** [AppliedAlpha/Brick-Pong#7]
> 공 클래스 만들고, 게임 화면 State에서 공이 기본 속력에 따라 움직이는 것을 확인

 <코드 상 항목>
- 기초 베이스 코드/환경 구성에 맞게 화면 사이즈에 대해 적절한 공의 객체 생성

- 화면 테투리와 공의 충돌 처리

- 스코어가 처리 된후, 공의 위치를 정중앙으로 다시 재배치

- 전체 소스에 합쳤을 때, 정상 구동 되는지 확인

**Comment by AppliedAlpha** [comment]
#8 에서 PR 완료
